[versions]
kotlin = "2.2.20"
lwjava = "1.2.0"
lwkotlin = "0.6.2"
kotest= "5.9.1"
dokka = "2.1.0"
jvm = "11"
antlr = "4.13.2"
gson = "2.13.2"
clikt = "5.0.3"
specs = "0.6.1"
testcontainers = "1.21.3"

[plugins]
build-config  = { id = "com.github.gmazzo.buildconfig", version = "5.7.0" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "13.1.0" }
release = { id ="net.researchgate.release", version = "3.1.0" }

[libraries]
guava = { group = "com.google.guava", name="guava", version="33.5.0-jre" } # Only used in tests
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
lionweb-java = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-core", version.ref = "lwjava" }
lionweb-java-client-testing = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-client-testing", version.ref = "lwjava" }
lionweb-kotlin = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-core", version.ref = "lwkotlin" }
lionweb-kotlin-client = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-client", version.ref = "lwkotlin" }
starlasu-specs = { module="com.strumenta.starlasu.specs:starlasuspecs-jvm", version.ref="specs" }
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }

antlr-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
commons-io = {module="commons-io:commons-io", version="2.20.0" }
slf4j = {module="org.slf4j:slf4j-simple", version="2.0.17" }
kotest-runner-junit5 = { module="io.kotest:kotest-runner-junit5-jvm", version.ref="kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit5 = { module="org.testcontainers:junit-jupiter", version.ref="testcontainers" }
testcontainers-pg = { module="org.testcontainers:postgresql", version.ref="testcontainers" }
